# Generated by Django 5.2.1 on 2025-05-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_code2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_verified_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
