# Generated by Django 5.2.1 on 2025-05-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_utilisateur_is_verified_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_verification',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email_verifie',
            field=models.BooleanField(default=False),
        ),
    ]
