# Generated by Django 5.2.1 on 2025-05-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_utilisateur_code_verification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='code_verification',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='email_verifie',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_verified_2fa',
        ),
    ]
