# Generated by Django 5.2.1 on 2025-05-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='montant_disponible',
        ),
    ]
