# Generated by Django 5.2.1 on 2025-05-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_budget_montant_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='niveau',
            field=models.CharField(choices=[('info', 'Info'), ('alerte', 'Alerte')], default='info', max_length=10),
        ),
    ]
