# Generated by Django 5.2.1 on 2025-05-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='depense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='core.depense'),
        ),
    ]
