# Generated by Django 5.2.1 on 2025-05-28 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_commande_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='core.fournisseur'),
        ),
    ]
