# Generated by Django 5.2.1 on 2025-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_commande_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignebudgetaire',
            name='montant_restant',
            field=models.FloatField(default=0, verbose_name='Montant restant de cette ligne'),
        ),
    ]
